% IndoorObstacleSet2 gives a set of obstacles for the ASL vicon arena
%
%   AUTHOR: Ross Allen, ASL, Stanford University
%   DATE:   July 9, 2015
%
%   Notes:
%       - tall rectangle obstacles
%		- written so that obstacle dimensions can be written on
%			the interval of [0,1] and auto scaled to the obstacleSpace
%			dimensions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function [LWH_F, YPR_F, CM_F] = IndoorObstacleSet2(obstacles)

envL = abs(obstacles.obstacleSpace(1,1) ...
	- obstacles.obstacleSpace(1,2));% (m) length of environment (x)
envW = abs(obstacles.obstacleSpace(2,1) ...
	- obstacles.obstacleSpace(2,2));% (m) length of environment (y)
envH = abs(obstacles.obstacleSpace(3,1) ...
	- obstacles.obstacleSpace(3,2));% (m) length of environment (z)

% Length/Width/Height of fixed cuboid obstacles (-) (m-th COLUMN vector corresponds to m-th obstacle)
LWH_F = [...
    [0.1, 0.1, 1.0]', ...
    [0.1, 0.1, 1.0]', ...
    [0.1, 0.1, 1.0]'];
LWH_F = LWH_F.*repmat([envL, envW, envH]', 1, 3);

% Yaw/Pitch/Roll of fixed cuboid obstacles (deg) (m-th COLUMN vector corresponds to m-th obstacle)
YPR_F = [...
    [0 0 0]', ...
    [0 0 0]', ...
    [0 0 0]'];

% Position vector of fixed cuboid obstacle centroid [m] (m-th COLUMN vector corresponds to m-th obstacle)
CM_F = [...
    [0.5, 0.5, 0.5]',...
    [0.4, 0.6, 0.5]', ...
    [0.6, 0.4, 0.5]'];
CM_F = CM_F.*repmat([envL, envW, envH]', 1, 3) + ...
	repmat([obstacles.obstacleSpace(1,1), ...
	 obstacles.obstacleSpace(2,1), ...
	obstacles.obstacleSpace(3,1)]', 1, 3);

end
