function feature_matrix = DSSCFeatureSetCost( stateMat1, stateMat2 )
    
    x_1         = stateMat1(:,1);
    y_1         = stateMat1(:,2);
    z_1         = stateMat1(:,3);
    xdot_1      = stateMat1(:,4);
    ydot_1      = stateMat1(:,5);
    zdot_1      = stateMat1(:,6);
    
    x_2         = stateMat2(:,1);
    y_2         = stateMat2(:,2);
    z_2         = stateMat2(:,3);
    xdot_2      = stateMat2(:,4);
    ydot_2      = stateMat2(:,5);
    zdot_2      = stateMat2(:,6);
       
    feature_matrix = [ ...
       
        x_1, ...
        y_1, ...
        z_1, ...
        xdot_1, ...
        ydot_1, ...
        zdot_1, ...
        x_2, ...
        y_2, ...
        z_2, ...
        xdot_2, ...
        ydot_2, ...
        zdot_2, ...
    ];
end
