function feature_matrix = SimpleUAVFeatureSetCost( stateMat1, stateMat2 )
    
    x_1         = stateMat1(:,1);
    y_1         = stateMat1(:,2);
    z_1         = stateMat1(:,3);
    theta_1      = stateMat1(:,4);
    
    x_2         = stateMat2(:,1);
    y_2         = stateMat2(:,2);
    z_2         = stateMat2(:,3);
    theta_2      = stateMat2(:,4);
       
    feature_matrix = [ ...
       
        x_1, ...
        y_1, ...
        z_1, ...
        theta_1, ...
        x_2, ...
        y_2, ...
        z_2, ...
        theta_2, ...
    ];
end